package filemanager

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

const MaxUploadSize int64 = 20 << 20

var idPattern = regexp.MustCompile(`^[a-f0-9]{32}$`)

var ErrNotFound = errors.New("file not found")
var ErrTooLarge = errors.New("file exceeds upload size limit")
var ErrEmptyFile = errors.New("empty files are not allowed")

type Association struct {
	Type string `json:"type,omitempty"`
	ID   string `json:"id,omitempty"`
}

type File struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	StoredName   string      `json:"stored_name"`
	ContentType  string      `json:"content_type"`
	Size         int64       `json:"size"`
	SHA256       string      `json:"sha256"`
	UploadedAt   time.Time   `json:"uploaded_at"`
	Association  Association `json:"association,omitempty"`
	DownloadURL  string      `json:"download_url,omitempty"`
}

// Store is the persistence boundary. A SQLite-backed implementation can replace
// this local JSON metadata store later while leaving upload HTTP handlers intact.
type Store interface {
	Save(name, contentType string, association Association, source io.Reader) (File, error)
	List() ([]File, error)
	Get(id string) (File, error)
	Open(id string) (File, io.ReadCloser, error)
	Delete(id string) error
	SetAssociation(id string, association Association) (File, error)
}

type localStore struct {
	mu       sync.RWMutex
	uploads  string
	metadata string
}

func NewStore(filesDir string) (Store, error) {
	uploads := filepath.Join(filesDir, "uploads")
	metadata := filepath.Join(filesDir, "metadata")
	for _, dir := range []string{uploads, metadata} {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return nil, fmt.Errorf("create file storage directory: %w", err)
		}
	}
	return &localStore{uploads: uploads, metadata: metadata}, nil
}

func (s *localStore) Save(name, contentType string, association Association, source io.Reader) (File, error) {
	id, err := newID()
	if err != nil {
		return File{}, err
	}
	ext := safeExtension(name)
	storedName := id + ext
	blobPath := filepath.Join(s.uploads, storedName)
	tmp, err := os.CreateTemp(s.uploads, ".upload-*")
	if err != nil {
		return File{}, fmt.Errorf("create upload: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	hash := sha256.New()
	size, err := io.Copy(io.MultiWriter(tmp, hash), io.LimitReader(source, MaxUploadSize+1))
	if err != nil {
		_ = tmp.Close()
		return File{}, fmt.Errorf("write upload: %w", err)
	}
	if size == 0 {
		_ = tmp.Close()
		return File{}, ErrEmptyFile
	}
	if size > MaxUploadSize {
		_ = tmp.Close()
		return File{}, ErrTooLarge
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return File{}, fmt.Errorf("sync upload: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return File{}, fmt.Errorf("close upload: %w", err)
	}

	record := File{
		ID:          id,
		Name:        safeDisplayName(name),
		StoredName:  storedName,
		ContentType: contentType,
		Size:        size,
		SHA256:      hex.EncodeToString(hash.Sum(nil)),
		UploadedAt:  time.Now().UTC(),
		Association: association,
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if err := os.Rename(tmpName, blobPath); err != nil {
		return File{}, fmt.Errorf("store uploaded file: %w", err)
	}
	if err := s.writeMetadata(record); err != nil {
		_ = os.Remove(blobPath)
		return File{}, err
	}
	return record, nil
}

func (s *localStore) List() ([]File, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	entries, err := os.ReadDir(s.metadata)
	if err != nil {
		return nil, fmt.Errorf("read file metadata: %w", err)
	}
	files := make([]File, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(s.metadata, entry.Name()))
		if err != nil {
			return nil, fmt.Errorf("read file metadata: %w", err)
		}
		var record File
		if err := json.Unmarshal(data, &record); err != nil {
			return nil, fmt.Errorf("decode file metadata %s: %w", entry.Name(), err)
		}
		record.DownloadURL = "/api/files/" + record.ID
		files = append(files, record)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].UploadedAt.After(files[j].UploadedAt) })
	return files, nil
}

func (s *localStore) Get(id string) (File, error) {
	if !idPattern.MatchString(id) {
		return File{}, ErrNotFound
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	record, err := s.readMetadata(id)
	if err != nil {
		return File{}, err
	}
	record.DownloadURL = "/api/files/" + record.ID
	return record, nil
}

func (s *localStore) Open(id string) (File, io.ReadCloser, error) {
	record, err := s.Get(id)
	if err != nil {
		return File{}, nil, err
	}
	// Stored names are generated by this package and must never contain paths.
	if filepath.Base(record.StoredName) != record.StoredName || !strings.HasPrefix(record.StoredName, record.ID) {
		return File{}, nil, errors.New("invalid stored file metadata")
	}
	file, err := os.Open(filepath.Join(s.uploads, record.StoredName))
	if errors.Is(err, os.ErrNotExist) {
		return File{}, nil, ErrNotFound
	}
	if err != nil {
		return File{}, nil, fmt.Errorf("open uploaded file: %w", err)
	}
	return record, file, nil
}

func (s *localStore) Delete(id string) error {
	if !idPattern.MatchString(id) {
		return ErrNotFound
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	record, err := s.readMetadata(id)
	if err != nil {
		return err
	}
	if filepath.Base(record.StoredName) != record.StoredName || !strings.HasPrefix(record.StoredName, record.ID) {
		return errors.New("invalid stored file metadata")
	}
	if err := os.Remove(filepath.Join(s.metadata, id+".json")); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove file metadata: %w", err)
	}
	if err := os.Remove(filepath.Join(s.uploads, record.StoredName)); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove uploaded file: %w", err)
	}
	return nil
}

func (s *localStore) SetAssociation(id string, association Association) (File, error) {
	if !idPattern.MatchString(id) {
		return File{}, ErrNotFound
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	record, err := s.readMetadata(id)
	if err != nil {
		return File{}, err
	}
	record.Association = association
	if err := s.writeMetadata(record); err != nil {
		return File{}, err
	}
	record.DownloadURL = "/api/files/" + record.ID
	return record, nil
}

func (s *localStore) readMetadata(id string) (File, error) {
	data, err := os.ReadFile(filepath.Join(s.metadata, id+".json"))
	if errors.Is(err, os.ErrNotExist) {
		return File{}, ErrNotFound
	}
	if err != nil {
		return File{}, fmt.Errorf("read file metadata: %w", err)
	}
	var record File
	if err := json.Unmarshal(data, &record); err != nil {
		return File{}, fmt.Errorf("decode file metadata: %w", err)
	}
	return record, nil
}

func (s *localStore) writeMetadata(record File) error {
	data, err := json.MarshalIndent(record, "", "  ")
	if err != nil {
		return fmt.Errorf("encode file metadata: %w", err)
	}
	tmp, err := os.CreateTemp(s.metadata, ".metadata-*")
	if err != nil {
		return fmt.Errorf("create file metadata: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write file metadata: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync file metadata: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close file metadata: %w", err)
	}
	if err := os.Rename(tmpName, filepath.Join(s.metadata, record.ID+".json")); err != nil {
		return fmt.Errorf("save file metadata: %w", err)
	}
	return nil
}

func newID() (string, error) {
	var id [16]byte
	if _, err := rand.Read(id[:]); err != nil {
		return "", fmt.Errorf("generate file ID: %w", err)
	}
	return hex.EncodeToString(id[:]), nil
}

func safeDisplayName(name string) string {
	name = strings.ReplaceAll(name, "\\", "/")
	name = filepath.Base(name)
	name = strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return '_'
		}
		return r
	}, name)
	name = strings.TrimSpace(name)
	if name == "" || name == "." {
		return "upload"
	}
	return name
}

func safeExtension(name string) string {
	ext := strings.ToLower(filepath.Ext(safeDisplayName(name)))
	if ext == "" {
		return ""
	}
	if len(ext) > 12 || strings.ContainsAny(ext, "/\\") {
		return ""
	}
	for _, r := range ext[1:] {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') {
			return ""
		}
	}
	return ext
}

