package forum

import "github.com/washsky/mygpt-test/internal/ui"

const forumPage = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>我的论坛</title>
<style>
:root{font:16px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;color:#18304a;background:#f5f7fb}
*{box-sizing:border-box}body{margin:0}button,input,textarea,select{font:inherit}a{color:#275bb9;text-decoration:none}a:hover{text-decoration:underline}
header{background:#fff;border-bottom:1px solid #dce5f0}header .wrap{width:min(1080px,100% - 32px);margin:auto;padding:20px 0;display:flex;justify-content:space-between;align-items:center;gap:15px}
h1{margin:0;font-size:26px}h2{margin:0 0 12px;font-size:21px}.muted{color:#63768c}.brand p{margin:2px 0 0}.nav{display:flex;gap:16px;white-space:nowrap}
main{width:min(1080px,100% - 32px);margin:28px auto;display:grid;grid-template-columns:230px minmax(0,1fr);gap:20px}.card{border:1px solid #dce5f0;border-radius:14px;background:white;padding:21px;box-shadow:0 4px 20px #1e345208;margin-bottom:20px}
.topic{display:block;border:0;background:transparent;width:100%;padding:10px;text-align:left;border-radius:9px;cursor:pointer;color:#18304a}.topic:hover,.topic.active{background:#e9f0fc;color:#2457b6}
.post{padding:16px 0;border-bottom:1px solid #e7edf4;cursor:pointer}.post:last-child{border:0}.post strong{display:block;font-size:18px}.post:hover strong{color:#2457b6}
label{display:block;margin:12px 0 5px;font-weight:650}input:not([type=checkbox]),select,textarea{width:100%;padding:10px;border:1px solid #ccd9e8;border-radius:9px;background:white;color:#18304a}textarea{min-height:145px;resize:vertical}button.primary{padding:10px 17px;margin-top:14px;background:#2b62c6;border:0;color:white;border-radius:9px;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.message{min-height:23px;color:#a5343d;white-space:pre-wrap}.body{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}.reply{border-top:1px solid #e5edf5;padding:16px 0}.reply .body{margin-top:8px}.attachment{display:inline-flex;gap:8px;padding:6px 9px;margin:6px 9px 6px 0;background:#edf3fc;border-radius:8px}
.small{font-size:13px}.hidden{display:none!important}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row button{flex:0 0 auto}.back{background:none;border:0;color:#275bb9;cursor:pointer;padding:0 0 12px}
.admin-tools{display:flex;gap:8px;margin:10px 0}.admin-button{border:1px solid #c9d7e8;border-radius:8px;background:#f7f9fc;color:#294361;padding:6px 10px;cursor:pointer}.admin-button.danger{color:#a33;border-color:#ead1d1}
.topic-row{display:flex;align-items:center;gap:5px}.topic-row .topic{flex:1;min-width:0}.topic-copy{border:0;background:transparent;color:#57708f;cursor:pointer;padding:6px;font-size:13px}.topic-copy:hover{color:#2457b6}.inline-image{display:block;max-width:min(100%,720px);max-height:70vh;margin:10px 0;border-radius:10px;object-fit:contain}.resource-video,.resource-audio{display:block;max-width:100%;margin:10px 0}.trash-entry{padding:14px 0;border-bottom:1px solid #e7edf4}.trash-entry:last-child{border:0}.post-preview{margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere;color:#52677f}.search-row{display:flex;gap:8px;margin:12px 0}.search-row input{flex:1}.search-row button{margin:0}
@media(max-width:720px){main{display:block}header .wrap{align-items:flex-start}.nav{flex-wrap:wrap}.card{padding:16px}}
</style>` + ui.Head + `<style>main{width:min(1180px,100% - 48px);grid-template-columns:220px minmax(0,1fr);gap:28px;margin-top:24px}aside .card{padding:18px}aside{align-self:start;position:sticky;top:20px}.post{padding:22px 4px}.post strong{font-size:20px}.post-link{color:var(--ink)}.post:hover strong{color:var(--accent)}.topic{color:var(--ink)}.topic:hover,.topic.active{background:var(--tint);color:var(--accent)}#detail{padding:32px}#detail-title{font-size:30px;line-height:1.4}#detail-body{padding:18px 0;font-size:16px}.reply{border-color:var(--line)}#editor{border-top:3px solid var(--accent)!important}#post-form{display:grid;gap:4px}#post-body{min-height:240px}#settings-form{max-width:720px}#settings-form>label:has(input[type=checkbox]){padding:12px;background:var(--soft);border-radius:10px}#trash-list h3{padding:12px 16px;background:var(--soft);border-radius:10px;margin-top:28px}.trash-entry{padding:18px 12px}.trash-entry strong{font-size:17px}#settings h3{border-top:1px solid var(--line);padding-top:22px;margin-top:26px}#feed-title{margin-bottom:4px}.feed-caption{margin-top:0}.draft-status{color:var(--muted);font-size:12px}#topics .admin-button{font-size:11px;padding:4px}.attachment a{white-space:nowrap}@media(max-width:720px){main{width:calc(100% - 32px);display:block}aside{position:static}#topics{display:flex;gap:6px;flex-wrap:wrap}.topic-row{max-width:100%}.topic-row .admin-button{font-size:11px;padding:4px}aside .workspace-shortcuts{display:none}#detail{padding:20px}#detail-title{font-size:25px}}</style></head><body>
` + ui.Nav + `
<main><aside><div class="card"><h2>主题</h2><div id="topics"></div><button class="primary" id="add-topic" type="button">添加主题</button><div id="topic-message" class="message small"></div></div><div class="card workspace-shortcuts"><h2>快捷入口</h2><a href="#compose">＋ 写一篇笔记</a><a href="/files">浏览全部资料 →</a><a href="/calculator">打开计算工具 →</a><a href="#trash">找回删除的内容 →</a></div></aside>
<div><div class="workspace-hero"><div><div class="eyebrow">个人知识空间</div><h1 id="site-title">我的论坛</h1><p id="site-description">记录想法，让资料彼此连接。</p></div><a class="workspace-link primary" href="#compose">＋ 写笔记</a></div><section id="feed"><div class="card"><h2 id="feed-title">全部笔记</h2><p class="muted small feed-caption">按主题整理记录，打开笔记查看正文、回复和附件。</p><form id="search-form" class="search-row hidden"><input id="search-query" maxlength="200" placeholder="搜索标题、正文或署名"><button class="primary" type="submit">搜索</button><button class="admin-button" id="clear-search" type="button">清除</button></form><div id="posts">加载中…</div><button id="more" class="primary hidden" type="button">加载更多</button></div><div class="card" id="editor"><h2>写一篇笔记</h2><p id="draft-status" class="draft-status">文字草稿自动保存在当前浏览器，附件需重新选择。</p><form id="post-form"><label for="post-topic">主题</label><select id="post-topic" required></select><label for="post-title">标题</label><input id="post-title" maxlength="200" required><label for="post-author">署名</label><input id="post-author" maxlength="80" required value="访客"><label for="post-body">正文（纯文本）</label><textarea id="post-body" maxlength="100000" required></textarea><p id="resource-help" class="muted small hidden">资源渲染开启后可识别 HTTPS 链接、Markdown 链接、Markdown 图片，例如 <code>![说明](https://example.com/image.jpg)</code>。输入的 HTML 不会执行。</p><label for="post-files">附件（单文件最大 20 MB）</label><input id="post-files" type="file" multiple><button class="primary" type="submit">发布</button><div class="message" id="post-message"></div></form></div></section>
<section id="detail" class="card hidden"><button class="back" id="back">← 返回帖子列表</button><h2 id="detail-title"></h2><div id="post-tools"></div><div class="message" id="detail-message"></div><div class="muted small" id="detail-meta"></div><div class="body" id="detail-body"></div><div id="detail-files"></div><h2 style="margin-top:28px">回复</h2><div id="replies"></div><form id="reply-form"><label for="reply-author">访客署名（记住在此浏览器）</label><input id="reply-author" maxlength="80" required value="访客"><label for="reply-body">回复内容</label><textarea id="reply-body" maxlength="20000" placeholder="写下回复，或直接粘贴截图…"></textarea><p class="muted small">支持粘贴、拖入图片，也可选择附件。只有图片时也能发表；每个文件最大 20 MB。</p><div class="reply-compose-tools"><label class="workspace-link" for="reply-files">＋ 图片 / 附件</label><input id="reply-files" type="file" multiple><span id="visitor-note" class="muted small"></span></div><div id="reply-queue" class="reply-queue"></div><div id="reply-failed"></div><button id="retry-reply-files" type="button" class="admin-button" hidden>重试失败附件</button><button type="submit" class="primary">发表回复</button><div class="message" id="reply-message"></div></form></section>
<section id="trash" class="card hidden"><button class="back" id="trash-back">← 返回</button><div class="row"><h2>回收站</h2><button id="empty-trash" class="admin-button danger" type="button">清空回收站</button></div><p class="muted small">删除的帖子、回复和文件会暂存在这里。彻底删除后无法恢复。</p><div id="trash-list">加载中…</div></section>
<section id="settings" class="card hidden"><button class="back" id="settings-back">← 返回</button><h2>工作空间设置</h2><p class="muted">管理站点信息、内容显示和发布方式。</p><p class="muted small">管理员令牌保存在程序数据目录的 config/admin-token 中，仅在本次浏览器会话中使用。</p><form id="settings-form"><h3>管理身份</h3><label for="admin-token">管理员令牌</label><input id="admin-token" type="password" autocomplete="off"><h3>站点信息</h3><label for="setting-title">站点名称</label><input id="setting-title" maxlength="100" required><label for="setting-description">站点简介</label><textarea id="setting-description" maxlength="500"></textarea><h3>发布与阅读</h3><label><input type="checkbox" id="guest-posts"> 允许访客发布帖子</label><label><input type="checkbox" id="guest-replies"> 允许访客回复</label><label><input type="checkbox" id="resource-rendering"> 启用正文资源渲染（链接、图片和附件预览）</label><label><input type="checkbox" id="search-enabled"> 启用帖子搜索（标题、正文和署名）</label><h3>阅读、协作与连接</h3><p class="muted small">以下功能可独立开启，默认关闭。实时更新不会重新加载整页。</p><label><input type="checkbox" id="feature-client_info"> 显示访客浏览器环境（浏览器、系统、设备类型、语言、时区）</label><label><input type="checkbox" id="feature-quote_replies"> 引用回复</label><label><input type="checkbox" id="feature-line_numbers"> 显示正文行号与总行数</label><label><input type="checkbox" id="feature-line_copy"> 逐行快捷复制</label><label><input type="checkbox" id="feature-clipboard"> 共享剪贴板</label><label for="clipboard-ttl">共享记录有效期（分钟，1–10080）</label><input type="number" id="clipboard-ttl" min="1" max="10080" value="10" required><label><input type="checkbox" id="feature-realtime"> 服务器实时推送</label><label><input type="checkbox" id="feature-network_resilience"> 网络优化（超时与只读重试）</label><p class="muted small">共享历史保存在数据目录，最多 50 条；所有能访问本站的设备都可查看、编辑和删除。关闭功能会清空历史。开启实时推送可收到共享更新；关闭后可手动刷新。</p><button type="submit" class="primary">保存设置</button><div id="settings-message" class="message"></div></form></section></div></main>
<dialog id="edit-dialog"><form method="dialog"><h2 id="edit-heading">编辑内容</h2><label id="edit-title-label">标题<input id="edit-title" maxlength="200"></label><label>正文<textarea id="edit-body" maxlength="100000" required></textarea></label><div class="dialog-actions"><button value="cancel" formnovalidate>取消</button><button value="save" class="primary">保存修改</button></div></form></dialog><script>
const $=q=>document.querySelector(q);let currentTopic="",currentPost="",searchQuery="",offset=0,settings={},attachmentNotice={id:"",text:""};
const err=async r=>{if(!r.ok)throw new Error((await r.text()).trim());return r.status===204?null:r.json()};
try{$("#admin-token").value=sessionStorage.getItem("forum-admin-token")||""}catch(_){}
const key=()=>{try{return $("#admin-token").value.trim()||sessionStorage.getItem("forum-admin-token")||""}catch(_){return $("#admin-token").value.trim()}};
async function api(path,method="GET",body){return err(await fetch(path,{method,headers:{"Content-Type":"application/json",...(key()?{"X-Admin-Token":key()}:{})},body:body?JSON.stringify(body):undefined}))}
function show(id){for(const name of ["feed","detail","trash","settings"])$("#"+name).classList.toggle("hidden",name!==id)}
function date(value){return new Date(value).toLocaleString()}
function clientTimezone(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||''}catch(_){return ''}}
function visitorInfo(author,created,extra,client){const row=make('div','','visitor-info'),avatar=make('span',(author||'访客').slice(0,1),'visitor-avatar'),info=make('div',''),name=make('strong',author||'访客'),time=document.createElement('time');time.dateTime=created;time.title=date(created);time.textContent=date(created);info.append(name,document.createElement('br'),time);if(extra)info.append(make('span',' · '+extra,'muted small'));if(settings.enable_client_info&&client?.browser){const line=make('div','','client-summary');line.append(make('span',client.browser),make('span',client.os),make('span',client.device));if(client.language)line.append(make('span',client.language));if(client.timezone)line.append(make('span',client.timezone));info.append(line)}row.append(avatar,info);return row}
function compactActions(container,keep=1){window.workspaceCompactActions(container,keep)}
async function copyText(value,button){let copied=false;try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(value)}else{const field=document.createElement("textarea");field.value=value;field.style.position="fixed";field.style.opacity="0";document.body.append(field);field.select();const ok=document.execCommand("copy");field.remove();if(!ok)throw new Error("复制失败")};copied=true}catch(_){}const shared=await window.workspaceShareText?.(value);const old=button.textContent;button.textContent=copied?(shared?"已复制并共享":"已复制"):(shared?"已加入共享历史":"复制失败");setTimeout(()=>button.textContent=old,1600)}
function copyButton(value,label="复制"){return adminButton(label,event=>copyText(value,event.currentTarget))}
function resourceURL(value){if(/^\/api\/files\/[a-f0-9]{32}(?:\/preview)?$/.test(value))return value;try{const url=new URL(value,location.href);return ["http:","https:"].includes(url.protocol)?url.href:""}catch{return ""}}
function imageURL(value){return value.startsWith("/api/files/")||(/^https:\/\//i.test(value)&&/\.(png|jpe?g|gif|webp)(?:[?#].*)?$/i.test(value))}
function appendText(target,value){const lines=value.split("\n");lines.forEach((line,index)=>{if(index)target.append(document.createElement("br"));target.append(document.createTextNode(line))})}
function plainResourceContent(target,value){target.replaceChildren();if(!settings.enable_resource_rendering){target.textContent=value;return}const pattern=/!\[([^\]]*)\]\((https:\/\/[^\s)]+|\/api\/files\/[a-f0-9]{32}\/preview)\)|\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/api\/files\/[a-f0-9]{32}(?:\/preview)?)\)|(https?:\/\/[^\s<>]+)/g;let last=0,match;while((match=pattern.exec(value))){appendText(target,value.slice(last,match.index));const raw=match[2]||match[4]||match[5],url=resourceURL(raw),alt=match[1],label=match[3];if(!url){appendText(target,match[0]);last=pattern.lastIndex;continue}if((match[1]!==undefined||match[5]&&imageURL(raw))&&(url.startsWith(location.origin)||url.startsWith("/" )||url.startsWith("https://"))){const image=document.createElement("img");image.src=url;image.alt=alt||raw;image.loading="lazy";image.decoding="async";image.referrerPolicy="no-referrer";image.className="inline-image";target.append(image)}else{const link=document.createElement("a");link.href=url;link.textContent=label||raw;link.target="_blank";link.rel="noopener noreferrer";target.append(link)}last=pattern.lastIndex}appendText(target,value.slice(last))}
function resourceContent(target,value){
 target.replaceChildren();const lines=value.split('\n');
 const renderLine=(el,line)=>{const source=/^引用回复：\/#reply\/([a-f0-9]+)$/.exec(line);if(source&&settings.enable_quote_replies){const a=make('a','↪ 查看被引用回复');a.href='/#reply/'+source[1];el.append(a)}else{plainResourceContent(el,line);if(settings.enable_quote_replies&&line.startsWith('> '))el.classList.add('quote-line')}};
 if(!settings.enable_line_numbers&&!settings.enable_line_copy){if(!settings.enable_quote_replies){plainResourceContent(target,value);return}lines.forEach((line,i)=>{if(i)target.append(document.createElement('br'));const span=make('span','');renderLine(span,line);target.append(span)});return}
 if(settings.enable_line_numbers)target.append(make('div','共 '+lines.length+' 行','line-summary'));
 lines.forEach((line,i)=>{const row=make('div','','content-line');if(settings.enable_line_numbers){const number=make('span',String(i+1),'line-number');number.setAttribute('aria-label','第 '+(i+1)+' 行');row.append(number)}const text=make('div','','line-text');renderLine(text,line);if(!line)text.append(document.createElement('br'));row.append(text);if(settings.enable_line_copy){const button=copyButton(line,'复制');button.classList.add('line-copy');button.setAttribute('aria-label','复制第 '+(i+1)+' 行');row.append(button)}target.append(row)})
}
function attachments(target,files){target.replaceChildren();for(const file of files||[]){if(["image/png","image/jpeg","image/gif","image/webp"].includes(file.content_type)){const image=document.createElement("img");image.src=file.download_url+"/preview";image.alt=file.name;image.loading="lazy";image.className="inline-image";target.append(image)}const span=make("div","","attachment"),preview=make("a","预览"),download=make("a","下载");preview.href="/files/view/"+encodeURIComponent(file.id);preview.target="_blank";preview.rel="noopener noreferrer";download.href=file.download_url;span.append(make("span",file.name),preview,download);if(settings.enable_clipboard){const share=adminButton("发送到共享",async()=>{const ok=await window.workspaceShareFile?.(file);share.textContent=ok?"已发送":"发送失败";setTimeout(()=>share.textContent="发送到共享",1500)});span.append(share)}compactActions(span,2);target.append(span)}}
async function loadSettings(){settings=await api("/api/forum/settings");$("#feature-client_info").checked=!!settings.enable_client_info;$("#feature-quote_replies").checked=!!settings.enable_quote_replies;$("#feature-line_numbers").checked=!!settings.enable_line_numbers;$("#feature-line_copy").checked=!!settings.enable_line_copy;$("#feature-clipboard").checked=!!settings.enable_clipboard;$("#clipboard-ttl").value=settings.clipboard_ttl_minutes||10;$("#feature-realtime").checked=!!settings.enable_realtime;$("#feature-network_resilience").checked=!!settings.enable_network_resilience;$("#site-title").textContent=settings.title;document.title=settings.title;$("#site-description").textContent=settings.description;$("#setting-title").value=settings.title;$("#setting-description").value=settings.description;$("#guest-posts").checked=settings.allow_guest_posts;$("#guest-replies").checked=settings.allow_guest_replies;$("#resource-rendering").checked=!!settings.enable_resource_rendering;$("#search-enabled").checked=!!settings.enable_search;$("#resource-help").classList.toggle("hidden",!settings.enable_resource_rendering);$("#search-form").classList.toggle("hidden",!settings.enable_search);if(!settings.enable_search){searchQuery="";$("#search-query").value=""}$("#editor").classList.toggle("hidden",!settings.allow_guest_posts&&!key())}
async function loadTopics(){const data=await api("/api/forum/topics");const container=$("#topics"),select=$("#post-topic");container.replaceChildren();select.replaceChildren();const all=make("button","全部主题","topic"+(currentTopic?"":" active"));all.onclick=()=>{currentTopic="";$("#feed-title").textContent="全部笔记";location.hash="";loadTopics();loadPosts(false)};container.append(all);for(const topic of data.items){const row=make("div","","topic-row"),button=make("button",topic.name,"topic"+(topic.id===currentTopic?" active":""));button.title=topic.description;button.onclick=()=>{currentTopic=topic.id;location.hash="";$("#feed-title").textContent=topic.name;loadTopics();loadPosts(false)};row.append(button,copyButton(topic.name+(topic.description?"\n"+topic.description:""),"复制主题"));container.append(row);const option=document.createElement("option");option.value=topic.id;option.textContent=topic.name;select.append(option)}if(currentTopic)select.value=currentTopic}
let feedRequest=0;
async function loadPosts(next){
 const request=++feedRequest;
 if(!next){offset=0;$("#posts").replaceChildren()}
 let path="/api/forum/posts?limit=20&offset="+offset;
 if(currentTopic)path+="&topic_id="+encodeURIComponent(currentTopic);
 if(searchQuery)path+="&q="+encodeURIComponent(searchQuery);
 const data=await api(path);
 if(request!==feedRequest)return;
 for(const post of data.items){
  const row=make("div","","post"),title=make("strong",post.title),meta=make("span",post.author+" · "+date(post.created_at)+" · "+post.reply_count+" 条回复","muted small");
  const postLink=make("a","","post-link");postLink.href="#post/"+encodeURIComponent(post.id);postLink.append(title);row.append(postLink,meta);
  if(searchQuery&&post.body)row.append(make("div",post.body.slice(0,220),"post-preview"));
  const copyValue=post.body?post.title+"\n\n"+post.body:post.title+"\n"+location.origin+"/#post/"+post.id;
  const tools=make("div","","admin-tools"),copy=copyButton(copyValue,post.body?"复制帖子内容":"复制标题和链接");
  copy.onclick=event=>{event.stopPropagation();copyText(copyValue,event.currentTarget)};
  tools.append(copy);row.append(tools);row.onclick=event=>{if(event.target.closest("button,a,details"))return;location.hash="post/"+post.id};$("#posts").append(row);
 }
 offset+=data.items.length;
 $("#more").classList.toggle("hidden",data.items.length<20);
 if(!offset)$("#posts").append(make("p",searchQuery?"没有找到匹配的帖子。":"这里还没有帖子，可以发布第一篇。","muted"));
}
async function showPost(id,replyID=""){
 const requestedHash=location.hash;
 if(currentPost!==id){$("#reply-body").value="";$("#reply-message").textContent=""}
 currentPost=id;show("detail");
 const post=await api("/api/forum/posts/"+encodeURIComponent(id));
 if(currentPost!==id||location.hash!==requestedHash)return;
 $("#detail-title").textContent=post.title;
 $("#detail-message").textContent=attachmentNotice.id===id?attachmentNotice.text:"";
 $("#detail-meta").replaceChildren(visitorInfo(post.author,post.created_at,post.replies.length+" 条回复 · "+(post.attachments||[]).length+" 个附件",post.client_info));
 resourceContent($("#detail-body"),post.body);
 attachments($("#detail-files"),post.attachments);
 const tools=$("#post-tools");tools.replaceChildren();
 const actions=make("div","","admin-tools");
 actions.append(copyButton(post.title+"\n\n"+post.body,"复制帖子内容"));
 actions.append(copyButton(location.origin+"/#post/"+id,"复制帖子链接"));const related=make("a","管理本篇附件","workspace-link");related.href="/files?related_type=post&related_id="+encodeURIComponent(id);actions.append(related);
 if(key()){
  actions.append(adminButton("编辑帖子",async()=>{
   const edited=await editContent("编辑笔记",post.title,post.body);if(!edited)return;const {title,body}=edited;
   try{await api("/api/forum/posts/"+encodeURIComponent(id),"PUT",{title,body});await showPost(id);await loadPosts(false)}
   catch(error){$("#detail-message").textContent=error.message}
  }));
  actions.append(adminButton("移入回收站",async()=>{
   if(!confirm("将帖子和回复移入回收站？附件会保留并可随帖子恢复。"))return;
   try{await api("/api/forum/posts/"+encodeURIComponent(id),"DELETE");location.hash="";show("feed");await loadPosts(false)}
   catch(error){$("#detail-message").textContent=error.message}
  },true));
 }
 compactActions(actions,1);tools.append(actions);
 const container=$("#replies");container.replaceChildren();
 for(const reply of post.replies){
  const row=make("div","","reply"),files=make("div",""),replyBody=make("div","","body");
  row.id="reply-"+reply.id;
  row.append(visitorInfo(reply.author,reply.created_at,"第 "+(post.replies.indexOf(reply)+1)+" 楼 · 当前笔记同署名回复 "+post.replies.filter(item=>item.author===reply.author).length+" 条 · "+(reply.attachments||[]).length+" 个附件",reply.client_info));
  resourceContent(replyBody,reply.body);row.append(replyBody,files);attachments(files,reply.attachments);
  const replyActions=make("div","","admin-tools");
  if(settings.enable_quote_replies&&(settings.allow_guest_replies||key()))replyActions.append(adminButton('引用回复',()=>{const field=$('#reply-body');const quote='引用回复：/#reply/'+reply.id+'\n'+(reply.author+'：\n'+reply.body.slice(0,1000)).split('\n').map(line=>'> '+line).join('\n')+'\n\n';if(field.value.length+quote.length>20000){$('#reply-message').textContent='引用后超出回复长度限制，请缩短正文。';return}field.value+=(field.value?'\n\n':'')+quote;field.focus();field.setSelectionRange(field.value.length,field.value.length);field.scrollIntoView({block:'center'})}));
  const relatedReply=make("a","管理回复附件","workspace-link");relatedReply.href="/files?related_type=reply&related_id="+encodeURIComponent(reply.id);replyActions.append(relatedReply);replyActions.append(copyButton(location.origin+"/#reply/"+reply.id,"复制回复链接"));
  replyActions.append(copyButton(reply.author+" · "+date(reply.created_at)+"\n"+reply.body,"复制回复"));
  if(key()){
   replyActions.append(adminButton("编辑回复",async()=>{
    const edited=await editContent("编辑回复",null,reply.body);if(!edited)return;const body=edited.body;
    try{await api("/api/forum/replies/"+encodeURIComponent(reply.id),"PUT",{body});await showPost(id)}
    catch(error){$("#reply-message").textContent=error.message}
   }));
   replyActions.append(adminButton("移入回收站",async()=>{
    if(!confirm("将这条回复移入回收站？附件会保留并可随回复恢复。"))return;
    try{await api("/api/forum/replies/"+encodeURIComponent(reply.id),"DELETE");await showPost(id);await loadPosts(false)}
    catch(error){$("#reply-message").textContent=error.message}
   },true));
  }
  compactActions(replyActions,settings.enable_quote_replies?1:0);row.append(replyActions);container.append(row);
 }
 if(replyID){const target=document.getElementById("reply-"+replyID);if(target){target.classList.add("focused");target.scrollIntoView({block:"center"})}else{$("#detail-message").textContent="已打开所属笔记，但这条回复未包含在当前显示范围内。"}}
 if(!post.replies.length)container.append(make("p","还没有回复。","muted"));
 $("#reply-form").classList.toggle("hidden",!settings.allow_guest_replies&&!key());
}
async function upload(input,type,id){const errors=[];for(const file of input.files){const form=new FormData();form.append("file",file);form.append("related_type",type);form.append("related_id",id);try{const res=await fetch("/api/files",{method:"POST",body:form});if(!res.ok)throw new Error((await res.text()).trim())}catch(e){errors.push(file.name+": "+e.message)}}input.value="";return errors}
async function loadTrash(){const container=$("#trash-list");if(!key()){const link=make("a","前往设置，填写管理员令牌","workspace-link");link.href="#settings";container.replaceChildren(make("p","回收站中的恢复与删除操作需要管理员令牌。","muted"),link);return}container.replaceChildren(make("p","加载回收站…","muted"));try{const [content,files]=await Promise.all([api("/api/forum/trash"),api("/api/files/trash")]);container.replaceChildren();const addSection=(title,items,render)=>{container.append(make("h3",title));if(!items.length){container.append(make("p","没有项目。","muted small"));return}for(const item of items)container.append(render(item))};addSection("已删除帖子",content.posts||[],item=>{const row=make("div","","trash-entry");row.append(make("strong",item.title),make("div",item.topic_name+" · "+item.author+" · 删除于 "+date(item.deleted_at),"muted small"),make("div",item.body.slice(0,240),"post-preview"));const actions=make("div","","admin-tools");actions.append(adminButton("恢复帖子",async()=>{try{await api("/api/forum/trash/posts/"+encodeURIComponent(item.id)+"/restore","POST");await loadTrash();await loadPosts(false)}catch(error){alert(error.message)}}),adminButton("彻底删除",async()=>{if(!confirm("彻底删除这篇帖子及其回复？附件文件本身会保留。"))return;try{await api("/api/forum/trash/posts/"+encodeURIComponent(item.id),"DELETE");await loadTrash()}catch(error){alert(error.message)}},true));row.append(actions);return row});addSection("已删除回复",content.replies||[],item=>{const row=make("div","","trash-entry");row.append(make("strong","回复于："+item.post_title),make("div",item.author+" · 删除于 "+date(item.deleted_at),"muted small"),make("div",item.body,"post-preview"));const actions=make("div","","admin-tools");actions.append(adminButton("恢复回复",async()=>{try{await api("/api/forum/trash/replies/"+encodeURIComponent(item.id)+"/restore","POST");await loadTrash();await loadPosts(false)}catch(error){alert(error.message)}}),adminButton("彻底删除",async()=>{if(!confirm("彻底删除这条回复？附件文件本身会保留。"))return;try{await api("/api/forum/trash/replies/"+encodeURIComponent(item.id),"DELETE");await loadTrash()}catch(error){alert(error.message)}},true));row.append(actions);return row});addSection("已删除文件",files.items||[],item=>{const row=make("div","","trash-entry");row.append(make("strong",item.name),make("div",item.size+" 字节 · 删除于 "+date(item.deleted_at),"muted small"));const actions=make("div","","admin-tools");actions.append(adminButton("恢复文件",async()=>{try{await api("/api/files/"+encodeURIComponent(item.id)+"/restore","POST");await loadTrash()}catch(error){alert(error.message)}}),adminButton("彻底删除",async()=>{if(!confirm("彻底删除文件 "+item.name+"？此操作无法恢复。"))return;try{await api("/api/files/"+encodeURIComponent(item.id)+"/purge","DELETE");await loadTrash()}catch(error){alert(error.message)}},true));row.append(actions);return row})}catch(error){container.replaceChildren(make("p",error.message,"message"))}}
$("#post-form").onsubmit=async e=>{e.preventDefault();const button=e.submitter,notice=$("#post-message");button.disabled=true;notice.textContent="发布中…";try{const post=await api("/api/forum/posts","POST",{topic_id:$("#post-topic").value,title:$("#post-title").value,body:$("#post-body").value,author:$("#post-author").value,timezone:clientTimezone()});const errors=await upload($("#post-files"),"post",post.id);$("#post-form").reset();try{localStorage.removeItem("workspace-post-draft")}catch(_){}attachmentNotice={id:post.id,text:errors.length?"帖子已发布，但这些附件失败：\n"+errors.join("\n"):""};notice.textContent="";location.hash="post/"+post.id;await showPost(post.id);await loadPosts(false)}catch(error){notice.textContent=error.message}finally{button.disabled=false;if(livePending)applyLive()}};
let replyQueue=[],replyFailed=[],replyBusy=false;
function imageFile(file){return ['image/png','image/jpeg','image/gif','image/webp'].includes(file.type)}
function addReplyFiles(files){if(replyBusy)return;let rejected=[];for(const file of files){if(!file.size||file.size>20*1024*1024){rejected.push(file.name);continue}replyQueue.push({file,url:imageFile(file)?URL.createObjectURL(file):''})}renderReplyQueue();if(rejected.length)$('#reply-message').textContent='未加入空文件或超过 20 MB 的文件：'+rejected.join('、')}
function renderReplyQueue(){const target=$('#reply-queue');target.replaceChildren();replyQueue.forEach((entry,index)=>{const card=make('div','','reply-file-card');if(entry.url){const img=document.createElement('img');img.src=entry.url;img.alt=entry.file.name;card.append(img)}card.append(make('span',entry.file.name+' · '+(entry.file.size/1024).toFixed(1)+' KB','small'));const remove=adminButton('移除',()=>{if(replyBusy)return;if(entry.url)URL.revokeObjectURL(entry.url);replyQueue.splice(index,1);renderReplyQueue()});remove.disabled=replyBusy;card.append(remove);target.append(card)});$('#reply-failed').replaceChildren();replyFailed.forEach((entry,index)=>{const row=make('div','','small message'),link=make('a','查看已发表回复');link.href='#reply/'+entry.replyID;row.append(make('span',entry.file.name+' 上传失败 · '),link,adminButton('放弃重试',()=>{if(replyBusy)return;replyFailed.splice(index,1);renderReplyQueue()}));$('#reply-failed').append(row)});$('#retry-reply-files').hidden=!replyFailed.length}
$('#reply-files').onchange=event=>{addReplyFiles(event.target.files);event.target.value=''};
$('#reply-body').addEventListener('paste',event=>{const files=Array.from(event.clipboardData?.files||[]).filter(imageFile);if(!files.length)return;event.preventDefault();addReplyFiles(files)});
$('#reply-body').addEventListener('dragover',event=>{if(event.dataTransfer?.types.includes('Files'))event.preventDefault()});$('#reply-body').addEventListener('drop',event=>{if(!event.dataTransfer?.files.length)return;event.preventDefault();addReplyFiles(event.dataTransfer.files)});
async function sendReplyFile(file,replyID){const form=new FormData();form.append('file',file);form.append('related_type','reply');form.append('related_id',replyID);const response=await fetch('/api/files',{method:'POST',body:form});if(!response.ok)throw Error((await response.text()).trim())}
function replyLock(locked){replyBusy=locked;for(const el of $('#reply-form').elements)el.disabled=locked;renderReplyQueue()}
$('#retry-reply-files').onclick=async()=>{if(replyBusy)return;replyLock(true);const failed=[];try{for(const entry of replyFailed){try{await sendReplyFile(entry.file,entry.replyID)}catch(_){failed.push(entry)}}replyFailed=failed;$('#reply-message').textContent=failed.length?'仍有附件失败，可继续重试；不会重复发表回复。':'附件重试成功。';if(currentPost)await showPost(currentPost)}finally{replyLock(false);if(livePending)applyLive()}};
$('#reply-form').onsubmit=async e=>{e.preventDefault();if(replyBusy)return;const postID=currentPost,body=$('#reply-body').value.trim(),batch=replyQueue.slice();if(!body&&!batch.length){$('#reply-message').textContent='请填写内容或加入图片、附件。';return}replyLock(true);$('#reply-message').textContent='发表中…';try{const reply=await api('/api/forum/posts/'+encodeURIComponent(postID)+'/replies','POST',{author:$('#reply-author').value,body:body||'分享附件',timezone:clientTimezone()});$('#reply-body').value='';replyQueue=[];for(let i=0;i<batch.length;i++){const entry=batch[i];$('#reply-message').textContent='上传附件 '+(i+1)+' / '+batch.length;try{await sendReplyFile(entry.file,reply.id)}catch(_){replyFailed.push({file:entry.file,replyID:reply.id})}finally{if(entry.url)URL.revokeObjectURL(entry.url)}}if(currentPost===postID)await showPost(postID);$('#reply-message').textContent=replyFailed.length?'回复已发表，部分附件失败；请使用下方重试。':'回复已发表。'}catch(error){$('#reply-message').textContent=error.message}finally{replyLock(false);if(livePending)applyLive()}};
function rememberVisitor(){const name=$('#reply-author').value.trim();try{localStorage.setItem('workspace-visitor-name',name)}catch(_){}$('#visitor-note').textContent='以 '+(name||'访客')+' 的署名发表；无需登录。'}
try{const name=localStorage.getItem('workspace-visitor-name');if(name){$('#reply-author').value=name;$('#post-author').value=name}}catch(_){}
$('#reply-author').addEventListener('input',()=>{$('#post-author').value=$('#reply-author').value;rememberVisitor()});$('#post-author').addEventListener('input',()=>{$('#reply-author').value=$('#post-author').value;rememberVisitor()});rememberVisitor();
$("#settings-form").onsubmit=async e=>{e.preventDefault();const message=$("#settings-message");try{try{sessionStorage.setItem("forum-admin-token",$("#admin-token").value.trim())}catch(_){}await api("/api/forum/settings","PUT",{title:$("#setting-title").value,description:$("#setting-description").value,allow_guest_posts:$("#guest-posts").checked,allow_guest_replies:$("#guest-replies").checked,enable_resource_rendering:$("#resource-rendering").checked,enable_search:$("#search-enabled").checked,enable_client_info:$("#feature-client_info").checked,enable_quote_replies:$("#feature-quote_replies").checked,enable_line_numbers:$("#feature-line_numbers").checked,enable_line_copy:$("#feature-line_copy").checked,enable_clipboard:$("#feature-clipboard").checked,clipboard_ttl_minutes:Number($("#clipboard-ttl").value),enable_realtime:$("#feature-realtime").checked,enable_network_resilience:$("#feature-network_resilience").checked});await loadSettings();document.getElementById("workspace-name").textContent=settings.title;window.dispatchEvent(new CustomEvent("workspace-settings-saved"));message.textContent="已保存"}catch(error){message.textContent=error.message}};
$("#add-topic").onclick=async()=>{const name=prompt("主题名称（需管理员令牌）");if(!name)return;const description=prompt("主题简介")||"";let token=key();if(!token){token=prompt("请输入数据目录 config/admin-token 中的管理员令牌")||"";sessionStorage.setItem("forum-admin-token",token)}try{await api("/api/forum/topics","POST",{name,description});$("#topic-message").textContent="主题已创建";await loadTopics()}catch(error){$("#topic-message").textContent=error.message}};
$("#more").onclick=()=>loadPosts(true).catch(e=>$("#posts").append(make("p",e.message,"message")));
$("#search-form").onsubmit=event=>{event.preventDefault();searchQuery=$("#search-query").value.trim();loadPosts(false).catch(error=>$("#posts").replaceChildren(make("p",error.message,"message")))};
$("#clear-search").onclick=()=>{$("#search-query").value="";searchQuery="";loadPosts(false).catch(error=>$("#posts").replaceChildren(make("p",error.message,"message")))};
$("#empty-trash").onclick=async()=>{if(!confirm("永久清空回收站中的帖子、回复和文件？此操作无法撤销。"))return;try{await api("/api/forum/trash","DELETE");await api("/api/files/trash","DELETE");await loadTrash()}catch(error){alert(error.message)}};
$("#back").onclick=()=>{location.hash=""};$("#settings-back").onclick=()=>{location.hash=""};$("#trash-back").onclick=()=>{location.hash=""};
async function route(){try{if(location.hash==="#settings"){show("settings");return}if(location.hash==="#trash"){show("trash");await loadTrash();return}if(location.hash==="#compose"){show("feed");$("#editor").classList.remove("hidden");$("#editor").scrollIntoView({block:"start"});$("#post-title").focus({preventScroll:true});return}if(location.hash.startsWith("#reply/")){const replyID=location.hash.slice(7);const parent=await api("/api/forum/replies/"+encodeURIComponent(replyID)+"/context");await showPost(parent.post_id,replyID);return}if(location.hash.startsWith("#post/")){await showPost(location.hash.slice(6));return}show("feed")}catch(error){show("detail");$("#detail-title").textContent="暂时无法打开内容";$("#post-tools").replaceChildren();$("#detail-files").replaceChildren();$("#replies").replaceChildren();$("#reply-form").classList.add("hidden");$("#detail-body").textContent="内容可能已删除，或连接失败。请返回列表重试。"}}

const draftFields=['post-title','post-body','post-author','post-topic'];
function restoreDraft(){try{const draft=JSON.parse(localStorage.getItem('workspace-post-draft')||'null');if(draft){for(const id of draftFields)if(typeof draft[id]==='string'&&document.getElementById(id))document.getElementById(id).value=draft[id];$('#draft-status').textContent='已恢复本地文字草稿；附件需重新选择。'}const transfer=JSON.parse(sessionStorage.getItem('workspace-calculation-note')||'null');if(transfer&&typeof transfer.body==='string'){if(!$('#post-title').value)$('#post-title').value='计算记录';$('#post-body').value+=($('#post-body').value?'\n\n':'')+transfer.body;sessionStorage.removeItem('workspace-calculation-note');saveDraft();}}catch(_){} }
function saveDraft(){try{const draft={};for(const id of draftFields)draft[id]=document.getElementById(id).value;localStorage.setItem('workspace-post-draft',JSON.stringify(draft));$('#draft-status').textContent='文字草稿已保存 · '+new Date().toLocaleTimeString()}catch(_) {$('#draft-status').textContent='浏览器无法保存草稿，请在离开前复制正文。'}}
$('#post-form').addEventListener('input',saveDraft);
function editContent(label,title,body){return new Promise(resolve=>{const dialog=$('#edit-dialog');$('#edit-heading').textContent=label;$('#edit-title-label').hidden=title===null;$('#edit-title').value=title||'';$('#edit-body').value=body;dialog.returnValue='';dialog.onclose=()=>resolve(dialog.returnValue==='save'?{title:$('#edit-title').value,body:$('#edit-body').value}:null);dialog.showModal()})}

let liveBusy=false,livePending=false;
async function applyLive(){if(liveBusy){livePending=true;return}if(document.hidden||$('#edit-dialog').open||Array.from(document.querySelectorAll('form button[type=submit]')).some(b=>b.disabled)){livePending=true;return}liveBusy=true;livePending=false;try{if(location.hash==='#settings'){return}await loadSettings();if(location.hash==='#trash'){await loadTrash()}else if(location.hash.startsWith('#post/')||location.hash.startsWith('#reply/')){const y=scrollY;await route();scrollTo(0,y)}else{await loadPosts(false)}}catch(_){$('#post-message').textContent='实时内容暂时未能加载，可重新连接后再试。'}finally{liveBusy=false;if(livePending&&!document.hidden)setTimeout(applyLive,300)}}
window.addEventListener('workspace-change',event=>{if(!event.detail.path||event.detail.path.startsWith('/api/forum/')||event.detail.path.startsWith('/api/files'))applyLive()});
window.addEventListener('visibilitychange',()=>{if(!document.hidden&&livePending)applyLive()});
$('#edit-dialog').addEventListener('close',()=>{if(livePending)applyLive()});
for(const id of ['post-body','reply-body','edit-body']){const input=document.getElementById(id),info=make('div','','line-summary');input.after(info);const update=()=>{info.hidden=!settings.enable_line_numbers;const before=input.value.slice(0,input.selectionStart),line=before.split('\n').length,column=before.length-before.lastIndexOf('\n');info.textContent='共 '+input.value.split('\n').length+' 行 · 光标第 '+line+' 行，第 '+column+' 列'};for(const event of ['input','click','keyup','select','focus'])input.addEventListener(event,update);window.addEventListener('workspace-options',event=>{settings.enable_line_numbers=!!event.detail.enable_line_numbers;update()});update()}
window.addEventListener("hashchange",route);
(async()=>{try{await loadSettings();await loadTopics();restoreDraft();await loadPosts(false);await route()}catch(error){$("#posts").textContent=error.message}})();
</script>` + ui.Foot + `</body></html>`
