package forum

const forumPage = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>我的论坛</title>
<style>
:root{font:16px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;color:#18304a;background:#f5f7fb}
*{box-sizing:border-box}body{margin:0}button,input,textarea,select{font:inherit}a{color:#275bb9;text-decoration:none}a:hover{text-decoration:underline}
header{background:#fff;border-bottom:1px solid #dce5f0}header .wrap{width:min(1080px,100% - 32px);margin:auto;padding:20px 0;display:flex;justify-content:space-between;align-items:center;gap:15px}
h1{margin:0;font-size:26px}h2{margin:0 0 12px;font-size:21px}.muted{color:#63768c}.brand p{margin:2px 0 0}.nav{display:flex;gap:16px;white-space:nowrap}
main{width:min(1080px,100% - 32px);margin:28px auto;display:grid;grid-template-columns:230px minmax(0,1fr);gap:20px}.card{border:1px solid #dce5f0;border-radius:14px;background:white;padding:21px;box-shadow:0 4px 20px #1e345208;margin-bottom:20px}
.topic{display:block;border:0;background:transparent;width:100%;padding:10px;text-align:left;border-radius:9px;cursor:pointer;color:#18304a}.topic:hover,.topic.active{background:#e9f0fc;color:#2457b6}
.post{padding:16px 0;border-bottom:1px solid #e7edf4;cursor:pointer}.post:last-child{border:0}.post strong{display:block;font-size:18px}.post:hover strong{color:#2457b6}
label{display:block;margin:12px 0 5px;font-weight:650}input:not([type=checkbox]),select,textarea{width:100%;padding:10px;border:1px solid #ccd9e8;border-radius:9px;background:white;color:#18304a}textarea{min-height:145px;resize:vertical}button.primary{padding:10px 17px;margin-top:14px;background:#2b62c6;border:0;color:white;border-radius:9px;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.message{min-height:23px;color:#a5343d;white-space:pre-wrap}.body{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}.reply{border-top:1px solid #e5edf5;padding:16px 0}.reply .body{margin-top:8px}.attachment{display:inline-flex;gap:8px;padding:6px 9px;margin:6px 9px 6px 0;background:#edf3fc;border-radius:8px}
.small{font-size:13px}.hidden{display:none!important}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row button{flex:0 0 auto}.back{background:none;border:0;color:#275bb9;cursor:pointer;padding:0 0 12px}
@media(max-width:720px){main{display:block}header .wrap{align-items:flex-start}.nav{flex-wrap:wrap}.card{padding:16px}}
</style></head><body>
<header><div class="wrap"><div class="brand"><h1 id="site-title">我的论坛</h1><p id="site-description" class="muted">分享想法，记录文章。</p></div><nav class="nav"><a href="/">首页</a><a href="/files">文件管理</a><a href="/calculator">计算器</a><a href="#settings" id="settings-link">设置</a></nav></div></header>
<main><aside><div class="card"><h2>主题</h2><div id="topics"></div><button class="primary" id="add-topic" type="button">添加主题</button><div id="topic-message" class="message small"></div></div></aside>
<div><section id="feed"><div class="card"><h2>最新帖子</h2><div id="posts">加载中…</div><button id="more" class="primary hidden" type="button">加载更多</button></div><div class="card" id="editor"><h2>发布帖子</h2><form id="post-form"><label for="post-topic">主题</label><select id="post-topic" required></select><label for="post-title">标题</label><input id="post-title" maxlength="200" required><label for="post-author">署名</label><input id="post-author" maxlength="80" required value="访客"><label for="post-body">正文（纯文本）</label><textarea id="post-body" maxlength="100000" required></textarea><label for="post-files">附件（单文件最大 20 MB）</label><input id="post-files" type="file" multiple><button class="primary" type="submit">发布</button><div class="message" id="post-message"></div></form></div></section>
<section id="detail" class="card hidden"><button class="back" id="back">← 返回帖子列表</button><h2 id="detail-title"></h2><div class="message" id="detail-message"></div><p class="muted small" id="detail-meta"></p><div class="body" id="detail-body"></div><div id="detail-files"></div><h2 style="margin-top:28px">回复</h2><div id="replies"></div><form id="reply-form"><label for="reply-author">署名</label><input id="reply-author" maxlength="80" required value="访客"><label for="reply-body">回复内容</label><textarea id="reply-body" maxlength="20000" required></textarea><label for="reply-files">附件</label><input id="reply-files" type="file" multiple><button type="submit" class="primary">发表回复</button><div class="message" id="reply-message"></div></form></section>
<section id="settings" class="card hidden"><button class="back" id="settings-back">← 返回</button><h2>论坛设置</h2><p class="muted small">管理员令牌保存在程序数据目录的 config/admin-token 中，仅在本次浏览器会话中使用。</p><form id="settings-form"><label for="admin-token">管理员令牌</label><input id="admin-token" type="password" autocomplete="off"><label for="setting-title">站点名称</label><input id="setting-title" maxlength="100" required><label for="setting-description">站点简介</label><textarea id="setting-description" maxlength="500"></textarea><label><input type="checkbox" id="guest-posts"> 允许访客发布帖子</label><label><input type="checkbox" id="guest-replies"> 允许访客回复</label><button type="submit" class="primary">保存设置</button><div id="settings-message" class="message"></div></form></section></div></main>
<script>
const $=q=>document.querySelector(q);let currentTopic="",currentPost="",offset=0,settings={},attachmentNotice={id:"",text:""};
const err=async r=>{if(!r.ok)throw new Error((await r.text()).trim());return r.json()};
const key=()=>$("#admin-token").value.trim()||sessionStorage.getItem("forum-admin-token")||"";
async function api(path,method="GET",body){return err(await fetch(path,{method,headers:{"Content-Type":"application/json",...(key()?{"X-Admin-Token":key()}:{})},body:body?JSON.stringify(body):undefined}))}
function show(id){for(const name of ["feed","detail","settings"])$("#"+name).classList.toggle("hidden",name!==id)}
function date(value){return new Date(value).toLocaleString()}
function make(tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el}
function attachments(target,files){target.replaceChildren();for(const file of files||[]){const span=make("span","","attachment"),preview=make("a","预览"),download=make("a","下载");preview.href=file.download_url+"/preview";preview.target="_blank";download.href=file.download_url;span.append(make("span",file.name),preview,download);target.append(span)}}
async function loadSettings(){settings=await api("/api/forum/settings");$("#site-title").textContent=settings.title;document.title=settings.title;$("#site-description").textContent=settings.description;$("#setting-title").value=settings.title;$("#setting-description").value=settings.description;$("#guest-posts").checked=settings.allow_guest_posts;$("#guest-replies").checked=settings.allow_guest_replies;$("#editor").classList.toggle("hidden",!settings.allow_guest_posts&&!key())}
async function loadTopics(){const data=await api("/api/forum/topics");const container=$("#topics"),select=$("#post-topic");container.replaceChildren();select.replaceChildren();const all=make("button","全部主题","topic"+(currentTopic?"":" active"));all.onclick=()=>{currentTopic="";loadTopics();loadPosts(false)};container.append(all);for(const topic of data.items){const button=make("button",topic.name,"topic"+(topic.id===currentTopic?" active":""));button.title=topic.description;button.onclick=()=>{currentTopic=topic.id;loadTopics();loadPosts(false)};container.append(button);const option=document.createElement("option");option.value=topic.id;option.textContent=topic.name;select.append(option)}if(currentTopic)select.value=currentTopic}
async function loadPosts(next){if(!next){offset=0;$("#posts").replaceChildren()}const data=await api("/api/forum/posts?limit=20&offset="+offset+(currentTopic?"&topic_id="+encodeURIComponent(currentTopic):""));for(const post of data.items){const row=make("div","","post");row.append(make("strong",post.title),make("span",post.author+" · "+date(post.created_at)+" · "+post.reply_count+" 条回复","muted small"));row.onclick=()=>{location.hash="post/"+post.id};$("#posts").append(row)}offset+=data.items.length;$("#more").classList.toggle("hidden",data.items.length<20);if(!offset)$("#posts").append(make("p","这里还没有帖子，可以发布第一篇。","muted"))}
async function showPost(id){currentPost=id;show("detail");const post=await api("/api/forum/posts/"+encodeURIComponent(id));$("#detail-title").textContent=post.title;$("#detail-message").textContent=attachmentNotice.id===id?attachmentNotice.text:"";$("#detail-meta").textContent=post.author+" · "+date(post.created_at);$("#detail-body").textContent=post.body;attachments($("#detail-files"),post.attachments);const container=$("#replies");container.replaceChildren();for(const reply of post.replies){const row=make("div","","reply"),files=make("div","");row.append(make("div",reply.author+" · "+date(reply.created_at),"muted small"),make("div",reply.body,"body"),files);attachments(files,reply.attachments);container.append(row)}if(!post.replies.length)container.append(make("p","还没有回复。","muted"));$("#reply-form").classList.toggle("hidden",!settings.allow_guest_replies&&!key())}
async function upload(input,type,id){const errors=[];for(const file of input.files){const form=new FormData();form.append("file",file);form.append("related_type",type);form.append("related_id",id);try{const res=await fetch("/api/files",{method:"POST",body:form});if(!res.ok)throw new Error((await res.text()).trim())}catch(e){errors.push(file.name+": "+e.message)}}input.value="";return errors}
$("#post-form").onsubmit=async e=>{e.preventDefault();const button=e.submitter,notice=$("#post-message");button.disabled=true;notice.textContent="发布中…";try{const post=await api("/api/forum/posts","POST",{topic_id:$("#post-topic").value,title:$("#post-title").value,body:$("#post-body").value,author:$("#post-author").value});const errors=await upload($("#post-files"),"post",post.id);$("#post-form").reset();attachmentNotice={id:post.id,text:errors.length?"帖子已发布，但这些附件失败：\n"+errors.join("\n"):""};notice.textContent="";location.hash="post/"+post.id;await showPost(post.id);await loadPosts(false)}catch(error){notice.textContent=error.message}finally{button.disabled=false}};
$("#reply-form").onsubmit=async e=>{e.preventDefault();const button=e.submitter,notice=$("#reply-message");button.disabled=true;notice.textContent="发表中…";try{const reply=await api("/api/forum/posts/"+encodeURIComponent(currentPost)+"/replies","POST",{author:$("#reply-author").value,body:$("#reply-body").value});const errors=await upload($("#reply-files"),"reply",reply.id);$("#reply-body").value="";await showPost(currentPost);notice.textContent=errors.length?"回复已发表，但附件失败：\n"+errors.join("\n"):""}catch(error){notice.textContent=error.message}finally{button.disabled=false}};
$("#settings-form").onsubmit=async e=>{e.preventDefault();const message=$("#settings-message");try{sessionStorage.setItem("forum-admin-token",$("#admin-token").value.trim());await api("/api/forum/settings","PUT",{title:$("#setting-title").value,description:$("#setting-description").value,allow_guest_posts:$("#guest-posts").checked,allow_guest_replies:$("#guest-replies").checked});await loadSettings();message.textContent="已保存"}catch(error){message.textContent=error.message}};
$("#add-topic").onclick=async()=>{const name=prompt("主题名称（需管理员令牌）");if(!name)return;const description=prompt("主题简介")||"";let token=key();if(!token){token=prompt("请输入数据目录 config/admin-token 中的管理员令牌")||"";sessionStorage.setItem("forum-admin-token",token)}try{await api("/api/forum/topics","POST",{name,description});$("#topic-message").textContent="主题已创建";await loadTopics()}catch(error){$("#topic-message").textContent=error.message}};
$("#more").onclick=()=>loadPosts(true).catch(e=>$("#posts").append(make("p",e.message,"message")));
$("#back").onclick=()=>{location.hash=""};$("#settings-back").onclick=()=>{location.hash=""};
async function route(){try{if(location.hash==="#settings"){show("settings");return}if(location.hash.startsWith("#post/")){await showPost(location.hash.slice(6));return}show("feed")}catch(error){$("#detail-body").textContent=error.message}}
window.addEventListener("hashchange",route);
(async()=>{try{await loadSettings();await loadTopics();await loadPosts(false);await route()}catch(error){$("#posts").textContent=error.message}})();
</script></body></html>`

