package ui

// Network is loaded before page scripts so every API request uses the same policy.
const Network = `<script>
(()=>{const original=window.fetch.bind(window);window.workspaceOptions={};window.workspaceCompactActions=(container,keep=1)=>{const nodes=Array.from(container.children);if(nodes.length<=keep+1)return;const details=document.createElement('details');details.className='action-menu';const summary=document.createElement('summary');summary.textContent='更多操作';const panel=document.createElement('div');panel.className='action-menu-panel';details.append(summary,panel);nodes.slice(keep).forEach(node=>panel.append(node));container.append(details)};window.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href),method=(init.method||(input instanceof Request?input.method:'GET')).toUpperCase();if(!window.workspaceOptions.enable_network_resilience||url.origin!==location.origin||!url.pathname.startsWith('/api/')||input instanceof Request||init.signal)return original(input,init);const read=method==='GET',attempts=read?2:1;for(let attempt=0;attempt<attempts;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),init.body instanceof FormData?300000:20000);try{const response=await original(input,{...init,signal:controller.signal,cache:read?'no-store':init.cache});const body=await response.arrayBuffer();return new Response([204,205,304].includes(response.status)?null:body,{status:response.status,statusText:response.statusText,headers:response.headers})}catch(error){if(attempt+1===attempts)throw Error(read?'连接超时或网络中断，请重试。':'连接中断，操作结果尚未确认。请先检查列表，避免重复提交。');await new Promise(resolve=>setTimeout(resolve,400+Math.random()*600))}finally{clearTimeout(timer)}}};})();
</script>`

const Live = `<style>.content-line{display:flex;gap:12px;align-items:flex-start;min-height:30px;border-bottom:1px solid var(--line);padding:3px 0}.line-number{flex:0 0 3em;text-align:right;color:var(--muted);font:12px/2.3 monospace;user-select:none}.line-text{flex:1;min-width:0;white-space:pre-wrap;overflow-wrap:anywhere}.line-copy{flex:0 0 auto;font-size:11px!important;padding:3px 8px!important}.line-summary{color:var(--muted);font-size:12px;padding:8px 0;white-space:normal}.quote-line{color:var(--muted);background:var(--soft)}#connection-status{font-size:12px;color:var(--muted);margin-left:auto}#clipboard-dialog{width:min(760px,calc(100% - 24px));max-height:90vh;overflow:auto}#clipboard-dialog textarea{width:100%;min-height:90px}#clipboard-dialog label{display:block;margin:12px 0}.clipboard-tools{display:flex;gap:8px;flex-wrap:wrap}.clipboard-tools button{padding:8px 12px;border:1px solid var(--line);border-radius:8px}.clipboard-entry{padding:14px 0;border-top:1px solid var(--line);overflow-wrap:anywhere}.clipboard-entry .clipboard-preview{white-space:pre-wrap;max-height:100px;overflow:hidden}.clipboard-entry textarea{min-height:130px}#clipboard-status{white-space:pre-wrap;color:var(--muted)}</style>
<dialog id="clipboard-dialog"><h2>共享剪贴板</h2><p class="muted">论坛中的复制会加入这里。你也可以发送文本或单个附件，在其他设备上接收。能访问本站的设备都能查看和修改历史。</p><label>发送文本<textarea id="clipboard-send" maxlength="32768" placeholder="在这里输入或粘贴文本"></textarea></label><div class="clipboard-tools"><button id="clipboard-paste" type="button">读取本机剪贴板</button><button id="clipboard-publish" type="button">发送文本</button><button id="clipboard-refresh" type="button">刷新历史</button><button id="clipboard-clear" type="button">清空历史</button></div><p id="clipboard-status" role="status"></p><h3>历史记录</h3><div id="clipboard-history"></div><div class="clipboard-tools"><button id="clipboard-close" type="button">关闭</button></div></dialog>
<script>
(()=>{const byID=id=>document.getElementById(id),status=document.createElement('span');status.id='connection-status';status.setAttribute('role','status');document.querySelector('.workspace-crumb').append(status);const clip=document.createElement('button');clip.type='button';clip.textContent='共享剪贴板';clip.hidden=true;document.querySelector('.workspace-nav').append(clip);let source=null,retry=null,watchdog=null,backoff=1000,settingsBusy=false,settingsPending=false;
function stop(){if(source)source.close();source=null;clearTimeout(retry);clearTimeout(watchdog)}
function emit(path){window.dispatchEvent(new CustomEvent('workspace-change',{detail:{path}}))}
function heartbeat(){clearTimeout(watchdog);watchdog=setTimeout(()=>reconnect(),65000)}
function reconnect(){stop();if(!window.workspaceOptions.enable_realtime)return;if(!navigator.onLine){status.textContent='离线 · 输入内容仍保留';return}status.textContent='连接中断 · 正在重连';retry=setTimeout(connect,backoff+Math.random()*500);backoff=Math.min(30000,backoff*2)}
function connect(){stop();if(!window.workspaceOptions.enable_realtime){status.textContent='实时更新已关闭';return}if(!navigator.onLine){status.textContent='离线';return}status.textContent='正在连接实时服务…';source=new EventSource('/api/events');heartbeat();source.addEventListener('ready',()=>{backoff=1000;status.textContent='实时已连接';heartbeat();emit('')});source.addEventListener('ping',heartbeat);source.addEventListener('change',event=>{heartbeat();let data;try{data=JSON.parse(event.data)}catch(_){return}if(data.path==='/api/forum/settings'||!data.path)loadOptions();if(data.path?.startsWith('/api/clipboard')){clip.textContent='剪贴板 · 有更新';if(byID('clipboard-dialog').open)refreshHistory()}emit(data.path)});source.addEventListener('disabled',()=>{stop();status.textContent='实时更新已关闭';loadOptions()});source.onerror=()=>reconnect()}
async function loadOptions(){if(settingsBusy){settingsPending=true;return}settingsBusy=true;try{const response=await fetch('/api/forum/settings');if(!response.ok)throw Error();const previous=window.workspaceOptions;window.workspaceOptions=await response.json();clip.hidden=!window.workspaceOptions.enable_clipboard;if(clip.hidden){if(byID('clipboard-dialog').open)byID('clipboard-dialog').close();byID('clipboard-history').replaceChildren()}window.dispatchEvent(new CustomEvent('workspace-options',{detail:window.workspaceOptions}));if(previous.enable_realtime!==window.workspaceOptions.enable_realtime||(!source&&!retry))connect()}catch(_){status.textContent='连接失败 · 可切回页面重试'}finally{settingsBusy=false;if(settingsPending){settingsPending=false;loadOptions()}}}
window.addEventListener('workspace-settings-saved',loadOptions);window.addEventListener('online',()=>{loadOptions();if(window.workspaceOptions.enable_realtime)connect()});window.addEventListener('offline',()=>{stop();status.textContent='离线 · 输入内容仍保留'});window.addEventListener('focus',loadOptions);window.addEventListener('pagehide',stop);window.addEventListener('pageshow',loadOptions);
const notice=text=>byID('clipboard-status').textContent=text;
async function relay(method,path='',body){const response=await fetch('/api/clipboard'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error(response.status===403?'共享剪贴板已关闭。':response.status===404?'文件或记录已删除。':response.status===400?'内容无效或文本超过 32 KiB。':'共享剪贴板请求失败，请重试。');return response.status===204?null:response.json()}
async function action(button,fn){button.disabled=true;try{await fn()}catch(error){notice(error.message)}finally{button.disabled=false}}
function button(label,callback){const el=document.createElement('button');el.type='button';el.textContent=label;el.onclick=event=>action(event.currentTarget,callback);return el}
async function localCopy(text){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();if(!document.execCommand('copy'))throw Error();field.remove()}return true}catch(_){return false}}
async function shareText(text){if(!window.workspaceOptions.enable_clipboard)return false;if(!text||new TextEncoder().encode(text).length>32768){notice('本地复制成功；共享记录最多 32 KiB。');return false}try{await relay('POST','',{kind:'text',text});if(byID('clipboard-dialog').open)refreshHistory();return true}catch(error){notice('本地复制成功；'+error.message);return false}}
window.workspaceShareText=shareText;
window.workspaceShareFile=async(file)=>{if(!window.workspaceOptions.enable_clipboard){notice('请先在设置中开启共享剪贴板。');return false}try{await relay('POST','',{kind:'file',file_id:file.id});notice('附件已加入共享历史。');if(byID('clipboard-dialog').open)refreshHistory();return true}catch(error){notice(error.message);return false}};
async function nativeFile(file){const response=await fetch('/api/files/'+encodeURIComponent(file.file_id));if(!response.ok)throw Error('文件不可用，请从文件资料页重新确认。');const blob=await response.blob();const native=new File([blob],file.name||'attachment',{type:blob.type||'application/octet-stream'});if(navigator.share&&navigator.canShare?.({files:[native]})){await navigator.share({files:[native],title:file.name});return}throw Error('浏览器不支持直接分享此文件，请使用下载按钮。')}
async function copyImage(file){if(!window.isSecureContext||!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw Error('此浏览器环境不允许写入图片，请下载图片或使用系统分享。');const response=await fetch('/api/files/'+encodeURIComponent(file.file_id)+'/preview');if(!response.ok)throw Error('图片已不可用。');const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error('此附件不是图片。');const bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close?.();const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error('无法转换图片。');await navigator.clipboard.write([new ClipboardItem({'image/png':png})]);notice('图片已复制到本机系统剪贴板。')}
async function refreshHistory(){if(!window.workspaceOptions.enable_clipboard)return;try{const data=await relay('GET');const target=byID('clipboard-history');target.replaceChildren();clip.textContent='共享剪贴板';if(!data.items.length){target.textContent='暂无历史记录。';return}for(const item of data.items){const row=document.createElement('article');row.className='clipboard-entry';const title=document.createElement('strong');title.textContent=item.kind==='file'?'附件 · '+item.name:'文本';const meta=document.createElement('div');meta.className='muted small';meta.textContent='发送 '+new Date(item.created_at).toLocaleString()+' · 到期 '+new Date(item.expires_at).toLocaleString();const preview=document.createElement('div');preview.className='clipboard-preview';preview.textContent=item.kind==='text'?item.text:'';const tools=document.createElement('div');tools.className='clipboard-tools';if(item.kind==='text'){tools.append(button('复制到本机',async()=>{if(!await localCopy(item.text))throw Error('浏览器禁止写入剪贴板，请手动选中文本。');notice('已复制。')}),button('编辑',async()=>{const field=document.createElement('textarea');field.value=item.text;preview.replaceWith(field);field.focus();tools.replaceChildren(button('保存修改',async()=>{if(!field.value||new TextEncoder().encode(field.value).length>32768)throw Error('请输入 1–32768 字节文本。');await relay('PUT','/'+encodeURIComponent(item.id),{text:field.value});await refreshHistory()}),button('取消',refreshHistory))}));}else{const url='/api/files/'+encodeURIComponent(item.file_id);const download=document.createElement('a');download.className='workspace-link';download.href=url;download.textContent='下载文件';const open=document.createElement('a');open.className='workspace-link';open.href='/files/view/'+encodeURIComponent(item.file_id);open.textContent='查看文件';tools.append(open,download,button('复制文件链接',async()=>{if(!await localCopy(location.origin+url))throw Error('浏览器禁止复制，请打开文件后复制地址。')}),button('设备分享',()=>nativeFile(item)));if(/\.(png|jpg|jpeg|gif|webp)$/i.test(item.name))tools.append(button('复制图片',()=>copyImage(item)))}tools.append(button('删除',async()=>{await relay('DELETE','/'+encodeURIComponent(item.id));await refreshHistory()}));window.workspaceCompactActions(tools,1);row.append(title,meta,preview,tools);target.append(row)}}catch(error){notice(error.message)}}
clip.onclick=()=>{byID('clipboard-dialog').showModal();refreshHistory()};byID('clipboard-close').onclick=()=>byID('clipboard-dialog').close();byID('clipboard-refresh').onclick=refreshHistory;
byID('clipboard-publish').onclick=event=>action(event.currentTarget,async()=>{const text=byID('clipboard-send').value;if(!text)throw Error('请输入文本。');await relay('POST','',{kind:'text',text});byID('clipboard-send').value='';notice('已加入共享历史。');await refreshHistory()});
byID('clipboard-clear').onclick=event=>action(event.currentTarget,async()=>{if(!confirm('清空全部共享历史？'))return;await relay('DELETE');await refreshHistory();notice('共享历史已清空。')});
byID('clipboard-paste').onclick=async()=>{try{byID('clipboard-send').value=await navigator.clipboard.readText();notice('已读取，点击发送后才会共享。')}catch(_){notice('浏览器不允许自动读取，请手动粘贴。');byID('clipboard-send').focus()}};
loadOptions();})();
</script>`
