package ui

// Network is loaded before page scripts so every API request uses the same policy.
const Network = `<script>
(()=>{const original=window.fetch.bind(window);window.workspaceOptions={};window.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href),method=(init.method||(input instanceof Request?input.method:'GET')).toUpperCase();if(!window.workspaceOptions.enable_network_resilience||url.origin!==location.origin||!url.pathname.startsWith('/api/')||input instanceof Request||init.signal)return original(input,init);const read=method==='GET',attempts=read?2:1;for(let attempt=0;attempt<attempts;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),init.body instanceof FormData?300000:20000);try{const response=await original(input,{...init,signal:controller.signal,cache:read?'no-store':init.cache});const body=await response.arrayBuffer();return new Response([204,205,304].includes(response.status)?null:body,{status:response.status,statusText:response.statusText,headers:response.headers})}catch(error){if(attempt+1===attempts)throw Error(read?'连接超时或网络中断，请重试。':'连接中断，操作结果尚未确认。请先检查列表，避免重复提交。');await new Promise(resolve=>setTimeout(resolve,400+Math.random()*600))}finally{clearTimeout(timer)}}};})();
</script>`

const Live = `<style>.content-line{display:flex;gap:12px;align-items:flex-start;min-height:30px;border-bottom:1px solid var(--line);padding:3px 0}.line-number{flex:0 0 3em;text-align:right;color:var(--muted);font:12px/2.3 monospace;user-select:none}.line-text{flex:1;min-width:0;white-space:pre-wrap;overflow-wrap:anywhere}.line-copy{flex:0 0 auto;font-size:11px!important;padding:3px 8px!important}.line-summary{color:var(--muted);font-size:12px;padding:8px 0;white-space:normal}.quote-line{color:var(--muted);background:var(--soft)}#connection-status{font-size:12px;color:var(--muted);margin-left:auto}#clipboard-dialog textarea{width:100%;min-height:160px}#clipboard-dialog input{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px}#clipboard-dialog label{display:block;margin:12px 0}.clipboard-tools{display:flex;gap:8px;flex-wrap:wrap}.clipboard-tools button{padding:8px 12px;border:1px solid var(--line);border-radius:8px}#clipboard-status{white-space:pre-wrap;color:var(--muted)}</style>
<dialog id="clipboard-dialog"><h2>跨设备文本剪贴板</h2><p class="muted">主动发送一段文本，在另一台设备接收并复制。仅中转最新一条，10 分钟过期，不保存到磁盘。</p><label>管理员令牌<input type="password" id="clipboard-token" autocomplete="off"></label><label>发送文本<textarea id="clipboard-send" maxlength="32768" placeholder="在这里粘贴要发送的文本"></textarea></label><div class="clipboard-tools"><button id="clipboard-paste">读取本机剪贴板</button><button id="clipboard-publish">发送文本</button><button id="clipboard-receive">接收最新文本</button><button id="clipboard-clear">清除中转内容</button></div><label>已接收<textarea id="clipboard-received" readonly></textarea></label><div class="clipboard-tools"><button id="clipboard-copy">复制接收内容</button><button id="clipboard-close">关闭</button></div><p id="clipboard-status" role="status"></p></dialog>
<script>
(()=>{const byID=id=>document.getElementById(id),status=document.createElement('span');status.id='connection-status';status.setAttribute('role','status');document.querySelector('.workspace-crumb').append(status);const clip=document.createElement('button');clip.type='button';clip.textContent='剪贴板';clip.hidden=true;document.querySelector('.workspace-nav').append(clip);let source=null,retry=null,watchdog=null,backoff=1000,settingsBusy=false,settingsPending=false;
function stop(){if(source)source.close();source=null;clearTimeout(retry);clearTimeout(watchdog)}
function emit(path){window.dispatchEvent(new CustomEvent('workspace-change',{detail:{path}}))}
function heartbeat(){clearTimeout(watchdog);watchdog=setTimeout(()=>reconnect(),65000)}
function reconnect(){stop();if(!window.workspaceOptions.enable_realtime)return;if(!navigator.onLine){status.textContent='离线 · 输入内容仍保留';return}status.textContent='连接中断 · 正在重连';retry=setTimeout(connect,backoff+Math.random()*500);backoff=Math.min(30000,backoff*2)}
function connect(){stop();if(!window.workspaceOptions.enable_realtime){status.textContent='实时更新已关闭';return}if(!navigator.onLine){status.textContent='离线';return}status.textContent='正在连接实时服务…';source=new EventSource('/api/events');heartbeat();source.addEventListener('ready',()=>{backoff=1000;status.textContent='实时已连接';heartbeat();emit('')});source.addEventListener('ping',heartbeat);source.addEventListener('change',event=>{heartbeat();let data;try{data=JSON.parse(event.data)}catch(_){return}if(data.path==='/api/forum/settings'||!data.path)loadOptions();if(data.path==='/api/clipboard'){clip.textContent='剪贴板 · 有更新';byID('clipboard-status').textContent='中转内容有更新，点击“接收最新文本”查看。'}emit(data.path)});source.addEventListener('disabled',()=>{stop();status.textContent='实时更新已关闭';loadOptions()});source.onerror=()=>reconnect()}
async function loadOptions(){if(settingsBusy){settingsPending=true;return}settingsBusy=true;try{const response=await fetch('/api/forum/settings');if(!response.ok)throw Error();const previous=window.workspaceOptions;window.workspaceOptions=await response.json();clip.hidden=!window.workspaceOptions.enable_clipboard;if(clip.hidden){byID('clipboard-dialog').close();byID('clipboard-received').value='';byID('clipboard-send').value=''}window.dispatchEvent(new CustomEvent('workspace-options',{detail:window.workspaceOptions}));if(previous.enable_realtime!==window.workspaceOptions.enable_realtime||(!source&&!retry))connect()}catch(_){status.textContent='连接失败 · 可切回页面重试'}finally{settingsBusy=false;if(settingsPending){settingsPending=false;loadOptions()}}}
window.addEventListener('workspace-settings-saved',loadOptions);window.addEventListener('online',()=>{loadOptions();if(window.workspaceOptions.enable_realtime)connect()});window.addEventListener('offline',()=>{stop();status.textContent='离线 · 输入内容仍保留'});window.addEventListener('focus',loadOptions);window.addEventListener('pagehide',stop);window.addEventListener('pageshow',loadOptions);
clip.onclick=()=>{try{byID('clipboard-token').value=document.getElementById('admin-token')?.value||sessionStorage.getItem('forum-admin-token')||''}catch(_){}byID('clipboard-dialog').showModal()};byID('clipboard-close').onclick=()=>byID('clipboard-dialog').close();
const notice=text=>byID('clipboard-status').textContent=text;
async function relay(method,text){const token=byID('clipboard-token').value.trim();if(!token)throw Error('请填写管理员令牌。');const response=await fetch('/api/clipboard',{method,headers:{'Content-Type':'application/json','X-Admin-Token':token},body:method==='PUT'?JSON.stringify({text}):undefined});if(!response.ok)throw Error(response.status===403?'功能未开启或管理员令牌不正确。':response.status===400?'文本过长，最多 32 KiB。':'请求失败，请重试。');return response.json()}
async function action(button,fn){button.disabled=true;try{await fn()}catch(error){notice(error.message)}finally{button.disabled=false}}
byID('clipboard-publish').onclick=event=>action(event.currentTarget,async()=>{const text=byID('clipboard-send').value;if(!text)throw Error('先粘贴或输入要发送的文本。');if(new TextEncoder().encode(text).length>32768)throw Error('文本最多 32 KiB，请缩短后再发送。');await relay('PUT',text);notice('已发送，另一台设备可接收；10 分钟后过期。')});
byID('clipboard-receive').onclick=event=>action(event.currentTarget,async()=>{const data=await relay('GET');byID('clipboard-received').value=data.text;clip.textContent='剪贴板';notice(data.text?'已接收，点击“复制接收内容”。':'暂无内容，可能已清除或过期。')});
byID('clipboard-clear').onclick=event=>action(event.currentTarget,async()=>{await relay('DELETE');byID('clipboard-received').value='';notice('中转内容已清除。')});
byID('clipboard-paste').onclick=async()=>{try{byID('clipboard-send').value=await navigator.clipboard.readText();notice('已读取，点击发送后才会上传。')}catch(_){notice('当前浏览器不允许读取，请手动粘贴到发送框。');byID('clipboard-send').focus()}};
byID('clipboard-copy').onclick=async()=>{const field=byID('clipboard-received');if(!field.value){notice('没有可复制的内容。');return}try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(field.value);else{field.focus();field.select();if(!document.execCommand('copy'))throw Error()}notice('已复制到本机剪贴板。')}catch(_){field.focus();field.select();notice('请使用系统复制操作复制已选中的文本。')}};
loadOptions();})();
</script>`
